# Generated by Django 4.2.7 on 2025-11-03 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name of the experiment', max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Automatic creation timestamp')),
                ('processing_start_time', models.DateTimeField(blank=True, help_text='Timestamp when processing started', null=True)),
                ('processing_end_time', models.DateTimeField(blank=True, help_text='Timestamp when processing ended', null=True)),
                ('calibration_file', models.CharField(help_text='Path to the .cal calibration file', max_length=500)),
                ('images_path', models.CharField(help_text='Path where the images are stored (RAM or SSD)', max_length=500)),
                ('used_parameters', models.TextField(default='{}', help_text='JSON string copy of all parameters used (for reproducibility)')),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('ERROR', 'Error'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current state of the experiment', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task ID for monitoring', max_length=255)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('notes', models.TextField(blank=True, help_text='Researcher notes and observations')),
            ],
            options={
                'verbose_name': 'Experiment',
                'verbose_name_plural': 'Experiments',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='PresetParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the preset', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this preset is for')),
                ('parameters', models.TextField(default='{}', help_text='JSON string containing all MyPTV parameters')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Automatic creation timestamp')),
                ('modification_date', models.DateTimeField(auto_now=True, help_text='Automatic last modification timestamp')),
            ],
            options={
                'verbose_name': 'Parameter Preset',
                'verbose_name_plural': 'Parameter Presets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Project's unique name", max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the project')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Automatic creation timestamp')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_file_path', models.CharField(help_text='Path to the .txt/.csv file containing trajectory data', max_length=500)),
                ('generation_date', models.DateTimeField(auto_now_add=True, help_text='Automatic generation timestamp')),
                ('key_metrics', models.TextField(default='{}', help_text='JSON string with calculated metrics (e.g. num_particles, frames_processed)')),
                ('additional_files', models.TextField(default='[]', help_text='JSON string list of paths to additional generated files')),
                ('experiment', models.OneToOneField(help_text='Associated experiment', on_delete=django.db.models.deletion.CASCADE, related_name='result', to='core.experiment')),
            ],
            options={
                'verbose_name': 'Result',
                'verbose_name_plural': 'Results',
            },
        ),
        migrations.AddField(
            model_name='experiment',
            name='project',
            field=models.ForeignKey(help_text='Project to which this experiment belongs', on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='core.project'),
        ),
    ]
